version: "3.0"
services:
  frot:
    build: ./packages/client/
    restart: always
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    # networks:
    #   - TicTacToe
    depends_on:
      - back
  back:
    build: ./packages/server/
    restart: always
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - DATABASE_ADDR=db
    # networks:
    #   - TicTacToe
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ofek
      POSTGRES_PASSWORD: ofekgabay
      POSTGRES_DB: main
    volumes:
      - /Users/Ofek/Documents/postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
    # networks:
    #   - TicTacToe
  adminer:
    image: adminer
    restart: always
    ports:
      - 8070:8080
    # networks:
    #   - TicTacToe
    depends_on:
      - db
# networks:
#   TicTacToe:
#     name: TicTacToe
#     driver: bridge
