version: "3.0"
services:
  frot:
    build: ./packages/client/
    restart: always
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    # networks:
    #   - TicTacToe
    depends_on:
      - back
  back:
    build: ./packages/server/
    restart: always
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - DATABASE_ADDR=db
    # networks:
    #   - TicTacToe
    depends_on:
      - db
      - mongo
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ofek
      POSTGRES_PASSWORD: ofekgabay
      POSTGRES_DB: main
    volumes:
      - /Users/Ofek/Documents/postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
    # networks:
    #   - TicTacToe
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ofek
      MONGO_INITDB_ROOT_PASSWORD: ofekgabay
    ports:
      - 27017:27017
    volumes:
      - ./config/mongod.conf:/etc/mongod.conf
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ofek
      ME_CONFIG_MONGODB_ADMINPASSWORD: ofekgabay
    depends_on:
      - mongo
  adminer:
    image: adminer
    restart: always
    ports:
      - 8070:8080
    # networks:
    #   - TicTacToe
    depends_on:
      - db
# networks:
#   TicTacToe:
#     name: TicTacToe
#     driver: bridge
